### ISSUE TITLE
Pearson logo in footer

### ISSUE THREAD

**Issue by Thurst-ft** [Financial-Times/o-footer#31]
In light of our recent change of propritor the Pearson branding probably needs removing from the o-footer.

**Comment by kaelig** [comment]
Sounds like a good one for @danskinner and his team.

**Comment by danskinner** [comment]
Good point.

I don't expect there's any immediate hurry - snr management have been saying it'll be between 2-4 months before the deal is finalised anyway.. but I shall make enquiries. Will have to be done at some point. But then it may need to be replaced with something from Nikkei perhaps, so might be worth waiting to see if we need to do a straight swap rather than do work on it twice.

**Comment by kaelig** [comment]
See #32 where I opened a PR/discussion to see if we can ease the change process by preparing the code for it.

**Comment by Thurst-ft** [comment]
@danskinner has there been any further discussion about branding in the footer?  We've been using o-footer with the Pearson branding across membership. It would be good to know if we just remove the Pearson strap line or if there is a Nikkei update coming to o-footer

**Comment by danskinner** [comment]
@Thurst-ft It's been progressing but nothing's been shared yet. I was told last week to expect something any day.

**Comment by alicebartlett** [comment]
Closing this as we have now released patch versions for all of the old versions of o-footer that were in use (^3.1, ^3.0, ^2.0 and ^4.1. ^1.2, ^3.2 will be released on Sunday 29th of Nov to time with the switchover date, as these are being used via the build service)
